SSA-NMCT2-DeschrijverPieterjan/Controllers/BandController.cs
using SSA_NMCT2_DeschrijverPieterjan.Models.DAL;
using SSA_NMCT2_DeschrijverPieterjan.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SSA_NMCT2_DeschrijverPieterjan.Controllers
{
    public class BandController : Controller
    {
        //
        // GET: /Band/

        public ActionResult Index(string SelectedDate)
        {
            ViewBag.Message = "De Line Up.";

            var ViewModel = new LineupVM();

            ViewModel.Dates = LineupRepository.GetAllDays();

            if (SelectedDate != null)
            {

                DateTime DTSelectedDate = Convert.ToDateTime(SelectedDate);
                string DTSelectedDate1 = DTSelectedDate.ToString("yyyy-MM-dd");

                ViewModel.LineUps = LineupRepository.GetLineupByDate(DTSelectedDate1);
                ViewModel.SelectedDate = SelectedDate;
            }
            else {
                ViewModel.LineUps = LineupRepository.GetLineup();
            }

            return View(ViewModel);
        }

        [AllowAnonymous]
        public ActionResult Details(string id)
        {
            BandLineUpVM model = new BandLineUpVM
            {
                Band = BandRepository.FindById(id),
                LineUp = LineupRepository.getLineUpByBand(Convert.ToInt32(id))
            };
            return View(model);
        }

        public PartialViewResult LineUp(int id)
        {
            return PartialView(LineupRepository.getLineUpByBand(id));
        }

    }
}

SSA-NMCT2-DeschrijverPieterjan/Controllers/NewsController.cs
using SSA_NMCT2_DeschrijverPieterjan.Models.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SSA_NMCT2_DeschrijverPieterjan.Controllers
{
    public class NewsController : Controller
    {
        //
        // GET: /News/

        public ActionResult Index()
        {
            //RSSController.GetFeed();
            return View(NewsRepository.getNews());
        }

    }
}

SSA-NMCT2-DeschrijverPieterjan/Controllers/TicketController.cs
using SSA_NMCT2_DeschrijverPieterjan.Models;
using SSA_NMCT2_DeschrijverPieterjan.Models.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebMatrix.WebData;

namespace SSA_NMCT2_DeschrijverPieterjan.Controllers
{
    public class TicketController : Controller
    {
        //
        // GET: /Ticket/
        [Authorize(Roles="Admin")]
        public ActionResult Index()
        {
            return View(TicketRepository.GetTickets());
        }

        [Authorize(Roles = "Admin, Visitor")]
        public ActionResult BestelTicket() {
            return View();
        }

        [HttpPost]
        public ActionResult BestelTicket(Ticket t) {
            string id = WebSecurity.CurrentUserId.ToString();
            User u = UserRepository.GetUserById(id);
            t.TicketHolderEmail = u.Email;
            TicketRepository.SetTicket(t);



            return RedirectToAction("OverzichtTicket", new { Email = u.Email});
        }


         [Authorize(Roles = "Admin, Visitor")]
        public ActionResult OverzichtTicket(string Email)
        {
            
            return View(TicketRepository.getTicketTypeByEmail(Email));
        }

        public ActionResult BevestigingBestelling() {
            return View();
        }
    }
}

SSA-NMCT2-DeschrijverPieterjan/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Moonrise Festival</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        @*<link rel="stylesheet" href="themes/MoonriseTheme.min.css" />*@
        <link rel="stylesheet" href="Site.css" />
        <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.0/jquery.mobile.structure-1.4.0.min.css" />
        <script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
        <script src="http://code.jquery.com/mobile/1.4.0/jquery.mobile-1.4.0.min.js"></script>
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
     <body>
     
        <header>
            <div class="content-wrapper" >
                <div class="float-left" >
                    <p class="site-title" >@Html.ActionLink("Moonrise Festival", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li class="test">@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Nieuws", "Index", "News")</li>
                            <li>@Html.ActionLink("Bands", "Index", "Band")</li>
                            <li>@Html.ActionLink("Bestel Tickets", "BestelTicket",  "Ticket")</li>
                           @* <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                            @if(Roles.IsUserInRole("Admin")){
                            <li>@Html.ActionLink("Tickets","Index","Ticket")</li>
                            }
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Moonrise Festival</p>
                    </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
        
    </body>
</html>